services:
    database:
        image: mysql:8.0.33
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3307:3306
        networks:
            - symfony_app

    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_var:/var/www/symfony/var
            - symfony_app_vendor:/var/www/symfony/vendor
        networks:
            - symfony_app 
        expose:
            - "9000" 
        env_file:
            - .env

    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_var:/var/www/symfony/var
            - symfony_app_vendor:/var/www/symfony/vendor
        ports:
            - 80:80
        depends_on:
            - php
        networks:
            - symfony_app

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - 8081:80
        depends_on:
            - database
        networks:
            - symfony_app

    mailhog:
        image: mailhog/mailhog 
        ports:
            - "1025:1025"  # SMTP Server
            - "8025:8025"  # Web UI
        networks:
            - symfony_app
    certbot:
        image: certbot/certbot
        volumes:
        - ./certbot/www:/var/www/certbot
        - ./certbot/conf:/etc/letsencrypt
        networks:
        - symfony_app
                
volumes:
    symfony_app_var:
    symfony_app_vendor:
    db_app:

networks:
    symfony_app: