name: CI/CD Pipeline for Dev

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main   

jobs:
  deploy:
    runs-on: ubuntu-latest
  #  needs: build  # Cette étape dépend de l'étape de  pour s'exécuter

    if: github.ref == 'refs/heads/main'  # Déploiement uniquement pour la branche dev

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 87.106.129.92 >> ~/.ssh/known_hosts
      # 1. Étape pour se connecter à ton VPS via SSH et déployer le code
      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" | ssh-add -
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            cd /../var/www/alphacorp
            git pull origin main
            cd .docker/
            docker-compose -f docker-compose.prod.yml up --build -d
          EOF
