name: CI/CD Pipeline for Dev

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main   
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Debug VPS_HOST
        run: |
          echo "VPS_HOST is: $VPS_HOST"
          echo "VPS_USER is: $VPS_USER"
          echo "SSH_PRIVATE_KEY is: $SSH_PRIVATE_KEY"
        
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add VPS to known hosts
        run: |
          ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts

      - name: Start SSH agent and add key
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            cd /var/www/alphacorp
            git pull origin main
            cd .docker/
            docker-compose -f docker-compose.prod.yml up --build -d
          EOF
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


