name: CI/CD Pipeline for Dev

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main   

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build  
    if: github.ref == 'refs/heads/main'  # Déploiement uniquement pour la branche dev

    steps:
      - name: Démarrer l'agent SSH et ajouter la clé
        run: |
          eval "$(ssh-agent -s)"
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Tester la connexion SSH
        run: ssh -o StrictHostKeyChecking=no user@vps-ip "echo 'Connexion réussie !'"
      # 1. Étape pour se connecter à ton VPS via SSH et déployer le code
      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" | ssh-add -
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            cd /../var/www/alphacorp
            git pull origin main
            cd .docker/
            docker-compose -f docker-compose.prod.yml up --build -d
          EOF
