name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Installer Docker et Docker Compose sur GitHub Actions
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      
      - name: Docker Compose Build
        run: |
          docker-compose -f docker-compose.yml build
          
      - name: Deploy to VPS
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USER: ${{ secrets.VPS_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        run: |
          # Ajoutez la clé privée SSH pour accéder à votre VPS
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Ajouter l'hôte à la liste des hôtes connus
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          
          # Déployer sur le VPS via SSH
          ssh $USER@$HOST << EOF
            cd /path/to/your/project
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF

