name: Symfony

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Docker
      run: |
        # Installer Docker et Docker Compose à l'intérieur du conteneur
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose

    - name: Build and run Symfony container
      run: |
        # Construire et démarrer les services définis dans docker-compose.yml à l'intérieur du conteneur
        cd .docker;
        docker-compose -f docker-compose.yml up -d

    - name: Set up environment variables for Symfony
      run: |
        echo "DATABASE_URL=mysql://symfony_user:symfony_password@mysql:3306/symfony_test_db" >> .env.test.local

    - name: Install Dependencies
      run: docker exec -T  symfony-php-1 composer install --no-dev

    - name: Wait for MySQL to be ready
      run: |
        # Attendre que MySQL soit prêt
        until docker exec -T mysql mysqladmin ping -h"127.0.0.1" --silent; do
          echo "Waiting for MySQL to be ready..."
          sleep 2
        done

    - name: Migrations
      run: docker exec -T  symfony-php-1 php bin/console doctrine:migrations:migrate --no-interaction

    - name: Fixtures
      run: docker exec -T  symfony-php-1 php bin/console doctrine:fixtures:load --no-interaction

